[app]
window_height = 1920.0
window_width = 1080.0

[game]
world_width = 2500.0
world_height = 2500.0
background_color = [
    163,
    116,
    46,
]
decoration_density = 0.0002777777
animation_tick_interval = 0.1

[sprite]
spritesheet_path = "sprites.png"
spritesheet_height = 8
spritesheet_width = 16
sprite_height = 32
sprite_width = 32
sprite_scale_factor = 1.5

[player]
movement_speed = 175.0
attack_interval = 1.0
projectile_speed = 600.0
projectile_damage = 1.0
movement_speed_multiplier_inc = 0.1
attack_speed_multiplier_inc = 0.1
xp_ball_pickup_range_multiplier_inc = 0.1
health_per_lvlup = 0.25

[enemy]
max_num_enemies = 50
enemy_spawn_interval = 2.0
enemy_health = 1.0
enemy_speed = 125.0
num_per_wave = 5
